### ISSUE TITLE
Astraea.py里哪个函数做了数据增强处理

### ISSUE THREAD

**Issue by Aston-zeal** [Sprinter1999/Astraea#1]
你好，首先很感谢您能复现Astraea的源码，降低了我的工作量。
其次，我有个问题想请教您一下，我粗略看了一下Astraea.py源码，不知道数据增强是在哪个函数里实现的，Astraea的第一步就是本地客户端内部的数据增强用于解决内部的数据异构性质。
希望您能解答一下，谢谢您

**Comment by Sprinter1999** [comment]
您好，这个repo核心的价值是提供rescheduling算法的实现，代码中没有添加数据增强相关的代码逻辑，您可以根据您的需要进行二次开发，欢迎您向本repo提供PR，我会code review后merge进来

**Comment by Aston-zeal** [comment]
多谢



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: Xuefen ***@***.***&gt;
发送时间: 2023年9月3日 16:48
收件人: Sprinter1999/Astraea ***@***.***&gt;
抄送: Aston ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [Sprinter1999/Astraea] Astraea.py里哪个函数做了数据增强处理 (Issue #1)





 
您好，这个repo核心的价值是提供rescheduling算法的实现，代码中没有添加数据增强相关的代码逻辑，您可以根据您的需要进行二次开发，欢迎您向本repo提供PR，我会code review后merge进来
