### ISSUE TITLE
kl_div_min不需要更新吗

### ISSUE THREAD

**Issue by Aston-zeal** [Sprinter1999/Astraea#2]
if(kl_div_temp < kl_div_min):
                        kl_div_min = kl_div_temp
                        target_K = client_idx
这当中，kl_div_min不需要更新成kl_div_min=kl_div_temp吗

**Comment by Sprinter1999** [comment]
我在赶一个要ddl的paper，10月份回复哈

**Comment by Aston-zeal** [comment]
> 我在赶一个要ddl的paper，10月份回复哈

多谢，意思就是不需要更改对吧

**Comment by Aston-zeal** [comment]
多谢
